name: Deploy Migrations
on:
  push:
    branches: [main]
    paths: ["packages/database/supabase/**"]
  workflow_dispatch:

jobs:
  supabase:
    name: Supabase Sync
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Install dependencies
        run: |
          npm ci
          npm ci --prefix ci

      - name: Run migrations
        run: npm run -w ci ci:migrations
